# Generated by Django 3.0.4 on 2020-03-31 20:30

from django.db import migrations


def execute(apps, schema_editor):
    # Get models
    Source = apps.get_model('jobs', 'Source')

    # Insert data
    Source.objects.create(
        name='Startit',
        url='https://startit.rs',
        first_page='/poslovi/',
        image='startit.png',
        is_active=True
    )
    Source.objects.create(
        name='Helloworld',
        url='https://www.helloworld.rs',
        first_page='/oglasi-za-posao/',
        image='helloworld.png',
        is_active=True
    )
    Source.objects.create(
        name='Infostud',
        url='https://poslovi.infostud.com',
        first_page='/oglasi-za-posao?category%5B0%5D=5',
        image='infostud.png',
        is_active=True
    )
    Source.objects.create(
        name='Jooble',
        url='https://rs.jooble.org',
        first_page='/posao-it/Srbija?p=1',
        image='jooble.png',
        is_active=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(execute),
    ]
