# Generated by Django 3.0.5 on 2020-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200407_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='image_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
