# Generated by Django 3.0.5 on 2020-04-08 13:58

from django.db import migrations


def execute(apps, schema_editor):
    # Get models
    Source = apps.get_model('jobs', 'Source')

    # Update data
    for s in Source.objects.all():
        s.image_name = s.image
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_source_image_name'),
    ]

    operations = [
        migrations.RunPython(execute),
    ]
