# Generated by Django 3.0.5 on 2020-04-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200408_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='image',
        ),
    ]
