# Generated by Django 3.0.5 on 2020-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='start_count',
            field=models.IntegerField(default=0),
        ),
    ]
