# Generated by Django 3.0.5 on 2020-04-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200417_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='image_name',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='large_image_name',
            new_name='large_image_path',
        ),
    ]
