# Generated by Django 3.0.5 on 2020-04-17 11:09

from django.db import migrations


def execute(apps, schema_editor):
    # Get models
    Source = apps.get_model('jobs', 'Source')

    # Update data
    for s in Source.objects.all():
        s.image_path = f'images/{s.image_path}'
        s.large_image_path = f'images/{s.large_image_path}'
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20200417_1309'),
    ]

    operations = [
        migrations.RunPython(execute),
    ]
